imports:
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      veneer_bosh_director_name: "%veneer_bosh.director_name%"
      veneer_bosh_plugin_factory: "@veneer_web.plugin.bundle.factory"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ ]
    bundles:
        - VeneerCoreBundle
    assets:
        highcharts_js:
            inputs:
                - "%kernel.root_dir%/../vendor/highslide-software/highcharts.com/js/highcharts.src.js"
        foundation_css:
            inputs:
                - "%kernel.root_dir%/../vendor/foundation/zurb/css/foundation.min.css"
        foundation_js:
            inputs:
                - "%kernel.root_dir%/../vendor/foundation/zurb/js/foundation.min.js"
        modernizr_js:
            inputs:
                - "%kernel.root_dir%/../vendor/foundation/zurb/js/vendor/modernizr.js"
        jquery_js:
            inputs:
                - "%kernel.root_dir%/../vendor/foundation/zurb/js/vendor/jquery.js"
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/../vendor/yuilibrary/build/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: bosh
        connections:
            state:
                driver: "pdo_sqlite"
                path: %kernel.root_dir%/state.sqlite
                charset:  UTF8
            bosh:
                driver:   "%database_adapter%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

    orm:
        default_entity_manager: bosh
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            state:
                connection: state
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    VeneerCoreBundle: ~
                    VeneerMarketplaceBundle: ~
            bosh:
                connection: bosh
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    VeneerBoshBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

veneer_marketplace:
    marketplaces:
        boshio:
            type: bosh-hub
