veneer_web:
    resource: "@VeneerCoreBundle/Resources/config/routing/default.xml"
veneer_bosh:
    resource: "@VeneerBoshBundle/Resources/config/routing/default.xml"
veneer_logsearch:
    resource: "@VeneerLogsearchBundle/Resources/config/routing/default.xml"
#veneer_cloque:
#    resource: "@VeneerCloqueBundle/Resources/config/routing/default.xml"
veneer_marketplace:
    resource: "@VeneerMarketplaceBundle/Resources/config/routing/default.xml"
veneer_ops:
    resource: "@VeneerOpsBundle/Resources/config/routing/default.xml"
