veneer_web:
    resource: "@VeneerCoreBundle/Resources/config/routing/default.xml"
veneer_bosh:
    resource: "@VeneerBoshBundle/Resources/config/routing/default.xml"
veneer_logsearch:
    resource: "@VeneerLogsearchBundle/Resources/config/routing/default.xml"
#veneer_cloque:
#    resource: "@VeneerCloqueBundle/Resources/config/routing/default.xml"
veneer_hub:
    resource: "@VeneerHubBundle/Resources/config/routing/default.xml"
veneer_bosh_editor:
    resource: "@VeneerBoshEditorBundle/Resources/config/routing/default.xml"
#veneer_awscpi:
#    resource: "@VeneerAwsCpiBundle/Resources/config/routing/default.xml"
veneer_wardencpi:
    resource: "@VeneerWardenCpiBundle/Resources/config/routing/default.xml"
#veneer_wellness:
#    resource: "@VeneerWellnessBundle/Resources/config/routing/default.xml"
veneer_sheaf:
    resource: "@VeneerSheafBundle/Resources/config/routing/default.xml"
